version: "3.0"

services:

  login-service:
    restart: on-failure
    build: ./
    networks:
      - default
      - taxi
    expose:
      - "8082"
    ports:
      - 8082-8085:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/TaxiService?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    external_links:
      - db-mysql
      - commom-service
      - redis-common

volumes:
  redis-data:
    driver: local

networks:
  default:
    external:
      name: external-network
  taxi:
    driver: bridge