
version: "3.0"

services:

  common-service:
    container_name: common-service
    restart: on-failure
    build: ./
    networks:
      - default
    expose:
      - "8080"
    ports:
      - 8080:8080

  redis-common:
    image: 'redis:alpine'
    container_name: "redis-common"
    hostname: redishost
    ports:
      - "6379:6379"
    networks:
      - default
      - taxi
    command: redis-server
    restart: always
    volumes:
      - redis-data:/usr/local/etc/redis.conf


  db-mysql:
    restart: always
    container_name: db-mysql
    image: mysql
    networks: [default]
    volumes:
      - ./mysql_init/docker.sql:/mysql_init/docker.sql
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: TaxiService
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --init-file="/mysql_init/docker.sql"
    ports:
      - "3307:3306"


volumes:
  redis-data:
    driver: local


networks:
  default:
    external:
      name: external-network
  taxi:
    driver: bridge