package com.test.taxiservice.taxiservicecommon.model.documentservice;

public enum DriverStatusEnum {
    PROFILE_UPDATE_IN_PROGRESS("PROFILE_UPDATE_IN_PROGRESS"),
    PROFILE_UPDATE_COMPLETED("PROFILE_UPDATE_COMPLETED"),
    DOCUMENT_UPLOAD_INPROGRESS("DOCUMENT_UPLOAD_INPROGRESS"),

    DOCUMENT_UPLOAD_COMPLETE("DOCUMENT_UPLOAD_COMPLETE"),
    BACKGROUND_VERIFICATION_INPROGRESS("BACKGROUND_VERIFICATION_INPROGRESS"),
    BACKGROUND_VERIFICATION_COMPLETED("BACKGROUND_VERIFICATION_COMPLETED"),
    BACKGROUND_VERIFICATION_FAILED("BACKGROUND_VERIFICATION_FAILED"),
    DEVICE_SHIPMENT_INPROGRESS("DEVICE_SHIPMENT_INPROGRESS"),
    DEVICE_SHIPMENT_COMPLETED("DEVICE_SHIPMENT_COMPLETED"),
    DEVICE_SHIPMENT_FAILED("DEVICE_SHIPMENT_FAILED"),

    ACTIVE("ACTIVE");

    private String value;

    DriverStatusEnum(String value) {
        this.value=value;
    }

    public String getValue() {
        return this.value;
    }
}
